workflows:
  web-build-workflow:
    name: Build React Vite Web App
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      node: 20
      
    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Build web project
        script: |
          npm run build
          
    artifacts:
      # This grabs your compiled web files
      - dist/ 
      
    publishing:
      email:
        recipients:
          - dularasandamal2@gmail.com
        notify:
          success: true
          failure: true
